### ISSUE TITLE
Java commands

### ISSUE THREAD

**Issue by NMichas** [crashub/mod-shell#12]
Adding Groovy commands under crash/commands works fine, however Java commands seem to be ignored. Are they actually supported in the first place? If they do, a quick howto would be helpful.

**Comment by vietj** [comment]
I will check soon, I need to update with latest candidate release anyway.

**Comment by NMichas** [comment]
My bad, it's working fine.

**Comment by vietj** [comment]
great! I plan to update it soon anyway since the latest CR have plenty of fixes
