### ISSUE TITLE
Vert-x3 plans?

### ISSUE THREAD

**Issue by kastork** [crashub/mod-shell#18]
Just curious whether there are plans to migrate this to vert-x3

**Comment by cinterloper** [comment]
+1

**Comment by vietj** [comment]
Hi, there are no plans to migrate to Vert.x 3 from me, however there are plans to implement a new solution to provide a more integrated solution with Vert.x 3. Get in touch on vertx-dev list to discuss this.

**Comment by jorgeuriarte** [comment]
Sorry... tried to find some references in vertx-dev list but got no luck.
Whats the status of that new solution integrated in Vert.x 3? Can we get any pointer?

**Comment by vietj** [comment]
Ah, I mean just that you can write on the vertx-dev list about it and we can discuss there :-) .

**Comment by vietj** [comment]
there is a thread on Vert.x google group about 3.1 features, you should mention you want a shell for Vert.x to increase its popularity and make it happen :-) https://groups.google.com/d/msg/vertx/5oDpfe3YhfA/2tHuwxc53KEJ
