### ISSUE TITLE
auto scan commands directory

### ISSUE THREAD

**Issue by luizalex** [crashub/mod-shell#3]
I`m using crashub with vert.x and I  notice when I add some new commands groovy into path (crash/commands) they don't appers after command help on shell. They only appers if I restart the crashub mod. Are there any missing configuration?

**Comment by vietj** [comment]
you should configure the property "crash.vfs.refresh_period" to a positive value like 1

**Comment by vietj** [comment]
the "cmd" property should also point to the location of the commands
